apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: image-registry
  namespace: openshift-image-registry
spec:
  host: image-registry.apps.cluster-aa0a.aa0a.sandbox28.opentlc.com
  port:
    targetPort: 5000-tcp
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: image-registry
